/**
 * presets.js — named configurations illustrating the behaviour classes of §10.
 * Each `config` is a partial patch applied over the current configuration.
 */

export const PRESETS = [
  {
    name: 'Default — binary threshold',
    description: 'Balanced starting point: 2-state, Moore(1), T = 4, mild integral memory.',
    config: {
      gridWidth: 120,
      gridHeight: 80,
      boundary: 'toroidal',
      neighborhood: 'moore',
      radius: 1,
      targetMode: 'constant',
      target: 4,
      kp: 1,
      ki: 0.02,
      kd: 0.4,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.35,
      stepsPerSecond: 20,
      overlay: 'none',
      cellSize: 6,
    },
  },
  {
    name: 'Under-damped ripples',
    description:
      'High Kp, low Kd: rippling wavefronts, oscillatory density rings, breathing clusters.',
    config: {
      kp: 2.4,
      ki: 0.01,
      kd: 0.05,
      integralClamp: true,
      integralMin: -6,
      integralMax: 6,
      target: 4,
      targetMode: 'constant',
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.4,
      stepsPerSecond: 24,
      overlay: 'none',
    },
  },
  {
    name: 'Critically-damped blobs',
    description: 'Balanced Kp/Kd: stable blobs, smooth morphogenesis, self-maintaining textures.',
    config: {
      kp: 0.9,
      ki: 0.015,
      kd: 0.85,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      target: 4,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.3,
      stepsPerSecond: 20,
      overlay: 'none',
    },
  },
  {
    name: 'Over-damped glassy creep',
    description: 'High Kd: slow creep, frozen-in patterns, metastable glassy states.',
    config: {
      kp: 0.35,
      ki: 0.005,
      kd: 2.2,
      integralClamp: true,
      integralMin: -10,
      integralMax: 10,
      target: 4,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.45,
      stepsPerSecond: 12,
      overlay: 'none',
    },
  },
  {
    name: 'Frustration vortices (I-field)',
    description:
      'Strong integral term with clamping; diagnostic overlay shows the accumulated-error field.',
    config: {
      kp: 0.5,
      ki: 0.18,
      kd: 0.25,
      integralClamp: true,
      integralMin: -6,
      integralMax: 6,
      target: 3.5,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      overlay: 'integral',
      overlayScale: 6,
      initialCondition: 'random',
      initialDensity: 0.3,
      stepsPerSecond: 18,
    },
  },
  {
    name: 'Semantic regulatory modes (3-state)',
    description:
      'State colour reports which PID term dominates: teal = integral-dominant, amber = P/D-driving.',
    config: {
      kp: 1.1,
      ki: 0.06,
      kd: 0.5,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      target: 4,
      stateCardinality: 3,
      expression: 'semantic',
      theta: 0,
      activePredicate: 'gt0',
      initialCondition: 'random',
      initialDensity: 0.32,
      overlay: 'none',
      stepsPerSecond: 20,
    },
  },
  {
    name: 'Quantised bands (3-state)',
    description: 'Ternary magnitude quantisation of u_t with band edges a < b.',
    config: {
      kp: 1.2,
      ki: 0.02,
      kd: 0.4,
      target: 4,
      stateCardinality: 3,
      expression: 'quantize',
      bandA: -0.6,
      bandB: 1.2,
      activePredicate: 'gt0',
      initialCondition: 'random',
      initialDensity: 0.3,
      stepsPerSecond: 20,
    },
  },
  {
    name: 'Stochastic annealing',
    description:
      'Probabilistic expression: σ(u_t) activation, soft boundaries, noise-driven exploration.',
    config: {
      kp: 0.8,
      ki: 0.02,
      kd: 0.3,
      target: 4,
      stateCardinality: 2,
      expression: 'probabilistic',
      theta: 0,
      sigmoidScale: 1.6,
      initialCondition: 'random',
      initialDensity: 0.35,
      stepsPerSecond: 20,
      overlay: 'none',
    },
  },
  {
    name: 'Programmable morphogenesis (radial T)',
    description: 'Spatially varying target field: dense core, sparse rim — shape-guided growth.',
    config: {
      gridWidth: 140,
      gridHeight: 100,
      cellSize: 5,
      targetMode: 'radial',
      target: 4,
      targetAmplitude: 3,
      kp: 1,
      ki: 0.03,
      kd: 0.5,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'center',
      initialDensity: 0.7,
      stepsPerSecond: 20,
      overlay: 'error',
      overlayScale: 6,
    },
  },
  {
    name: 'Breathing target (oscillating T)',
    description:
      'Time-varying target drives global density oscillation; watch the error overlay pulse.',
    config: {
      targetMode: 'oscillating',
      target: 4,
      targetAmplitude: 2,
      targetPeriod: 200,
      kp: 1.1,
      ki: 0.02,
      kd: 0.45,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.35,
      overlay: 'u',
      overlayScale: 6,
      stepsPerSecond: 30,
    },
  },
  {
    name: 'Painted target field (draw the setpoint)',
    description:
      'Target mode = painted. Switch Paint layer to "Target field T(c)" and draw with the brush, line, rectangle or text stamp — the texture grows to match what you drew.',
    config: {
      gridWidth: 160,
      gridHeight: 110,
      cellSize: 5,
      targetMode: 'painted',
      target: 2,
      kp: 1,
      ki: 0.03,
      kd: 0.5,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.35,
      paintLayer: 'target',
      targetTool: 'text',
      targetPaintValue: 6,
      targetBrushSize: 4,
      targetText: 'PID',
      targetFontSize: 40,
      targetTextBold: true,
      overlay: 'target',
      overlayScale: 6,
      stepsPerSecond: 20,
    },
  },
  {
    name: 'Text target field (auto-fit, multi-line)',
    description:
      'Target mode = text: the setpoint field is a centred, auto-fitted text block (newlines supported). The fit % constrains whichever of the rendered width % / height % is larger.',
    config: {
      gridWidth: 180,
      gridHeight: 110,
      cellSize: 4,
      targetMode: 'text',
      textFieldText: 'PID\nCA',
      textFieldFit: 80,
      textFieldValue: 6,
      textFieldBold: true,
      textFieldLineHeight: 1.05,
      target: 2,
      kp: 1,
      ki: 0.03,
      kd: 0.5,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.35,
      overlay: 'target',
      overlayScale: 6,
      stepsPerSecond: 20,
    },
  },
  {
    name: 'Self-healing texture (paint to damage)',
    description:
      'Stable texture with fixed borders — clear a region by shift-dragging and watch it regrow.',
    config: {
      boundary: 'fixed',
      neighborhood: 'moore',
      radius: 1,
      kp: 0.9,
      ki: 0.04,
      kd: 0.7,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      target: 4,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.35,
      cellSize: 8,
      gridWidth: 90,
      gridHeight: 60,
      stepsPerSecond: 15,
    },
  },
  {
    name: 'Wide von Neumann radius 3',
    description:
      'Larger neighbourhood with a proportionally larger target: coarse, slow-moving structure.',
    config: {
      neighborhood: 'vonNeumann',
      radius: 3,
      target: 7,
      kp: 0.7,
      ki: 0.02,
      kd: 0.5,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.4,
      stepsPerSecond: 15,
    },
  },
  // ---------------------------------------------------------------------
  // Custom link tables + signed state ranges
  // ---------------------------------------------------------------------
  {
    name: 'Custom link table — knight moves',
    description:
      'Radius-2 custom neighbourhood with only the eight knight-move links enabled: non-local, interleaved lattices.',
    config: {
      neighborhood: 'custom',
      radius: 2,
      // 5×5 row-major table (y = −2 … +2): the eight (±1,±2)/(±2,±1) links.
      neighborhoodMask: '0101010001000001000101010',
      neighborMetric: 'count',
      activePredicate: 'gt0',
      target: 3,
      kp: 1,
      ki: 0.02,
      kd: 0.4,
      stateMin: 0,
      stateMax: 1,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.35,
      stepsPerSecond: 20,
      overlay: 'none',
    },
  },
  {
    name: 'Custom link table — anisotropic cross',
    description:
      'Only the horizontal links of a radius-2 window are enabled: growth becomes strongly directional.',
    config: {
      neighborhood: 'custom',
      radius: 2,
      neighborhoodMask: '0000000000110110000000000',
      target: 2,
      kp: 1.1,
      ki: 0.03,
      kd: 0.4,
      stateMin: 0,
      stateMax: 1,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.3,
      stepsPerSecond: 20,
    },
  },
  {
    name: 'Bipolar domains (signed ±3)',
    description:
      'Signed state range with a saturating expression: positive and negative domains compete across a signed neighbour sum.',
    config: {
      neighborhood: 'moore',
      radius: 1,
      neighborMetric: 'sum',
      target: 0,
      targetMode: 'constant',
      kp: 0.8,
      ki: 0.01,
      kd: 0.35,
      integralClamp: true,
      integralMin: -6,
      integralMax: 6,
      stateMin: -3,
      stateMax: 3,
      expression: 'signed',
      theta: 0.5,
      initialCondition: 'random',
      initialDensity: 0.5,
      stepsPerSecond: 20,
      overlay: 'none',
    },
  },
  {
    name: 'Signed level field (−6 … +6)',
    description:
      'Thirteen-level signed expression: u_t is quantised linearly into the range, giving smooth grey-scale morphogenesis.',
    config: {
      neighborMetric: 'sum',
      target: 0,
      kp: 0.55,
      ki: 0.012,
      kd: 0.45,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      stateMin: -6,
      stateMax: 6,
      expression: 'levels',
      levelGain: 0.9,
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.45,
      stepsPerSecond: 24,
      overlay: 'u',
      overlayScale: 8,
    },
  },
  // ---------------------------------------------------------------------
  // Bioelectrical membrane domain (bioelectrical.md §8 behaviour classes)
  // ---------------------------------------------------------------------
  {
    name: 'Membrane — quiescence (baseline)',
    description:
      'Sanity baseline: weak coupling, noisy rest relaxes back to V_rest and stays there.',
    config: {
      mode: 'membrane-only',
      gridWidth: 120,
      gridHeight: 80,
      cellSize: 6,
      boundary: 'fixed',
      neighborhood: 'moore',
      radius: 1,
      vRest: -70,
      vThreshold: -55,
      vClose: -60,
      vRelease: -90,
      vMin: -100,
      vMax: 40,
      kLeak: 0.08,
      kCoupling: 0.02,
      kRelease: 0.6,
      polarity: 'depolarizing',
      closeMode: 'hysteresis',
      minOpenTicks: 1,
      resetPeriod: 6,
      membraneInit: 'noisy-rest',
      membraneJitter: 4,
      noiseAmplitude: 0,
      overlay: 'voltage',
      stepsPerSecond: 30,
    },
  },
  {
    name: 'Membrane — single propagating wavefront',
    description:
      'Core validation case: a seeded spike expands as an annular wave; refractoriness blocks back-propagation.',
    config: {
      mode: 'membrane-only',
      gridWidth: 140,
      gridHeight: 100,
      cellSize: 5,
      boundary: 'fixed',
      neighborhood: 'moore',
      radius: 1,
      vRest: -70,
      vThreshold: -55,
      vClose: -60,
      vRelease: -90,
      kLeak: 0.05,
      kCoupling: 0.09,
      kRelease: 0.6,
      closeMode: 'hysteresis',
      minOpenTicks: 2,
      resetPeriod: 8,
      membraneInit: 'seeded-spike',
      noiseAmplitude: 0,
      overlay: 'none',
      stepsPerSecond: 30,
      membraneTool: 'stimulus',
      stimulusAmplitude: 12,
      stimulusMode: 'pulse',
    },
  },
  {
    name: 'Membrane — spiral waves / reentry',
    description:
      'Excitable turbulence from noisy rest; clamp a band (paint tool → clamp) to break a front into a spiral.',
    config: {
      mode: 'membrane-only',
      gridWidth: 160,
      gridHeight: 110,
      cellSize: 4,
      boundary: 'toroidal',
      neighborhood: 'moore',
      radius: 1,
      vRest: -70,
      vThreshold: -58,
      vClose: -62,
      vRelease: -88,
      kLeak: 0.04,
      kCoupling: 0.1,
      kRelease: 0.55,
      closeMode: 'hysteresis',
      minOpenTicks: 2,
      resetPeriod: 10,
      membraneInit: 'noisy-rest',
      membraneJitter: 9,
      noiseAmplitude: 0,
      overlay: 'none',
      stepsPerSecond: 40,
      membraneTool: 'clamp',
      clampVoltage: -95,
    },
  },
  {
    name: 'Membrane — pacemaker train',
    description:
      'A clamped depolarized centre cell emits periodic waves at a rate set by resetPeriod + minOpenTicks.',
    config: {
      mode: 'membrane-only',
      gridWidth: 140,
      gridHeight: 100,
      cellSize: 5,
      boundary: 'fixed',
      vRest: -70,
      vThreshold: -55,
      vClose: -60,
      vRelease: -90,
      kLeak: 0.05,
      kCoupling: 0.085,
      kRelease: 0.6,
      closeMode: 'timed',
      minOpenTicks: 3,
      resetPeriod: 12,
      membraneInit: 'pacemaker',
      clampVoltage: -20,
      membraneTool: 'clamp',
      overlay: 'none',
      stepsPerSecond: 30,
    },
  },
  {
    name: 'Membrane — timed pulse generator',
    description:
      'closeMode: timed — gate width is exactly minOpenTicks. Widen it to thicken the wavefront.',
    config: {
      mode: 'membrane-only',
      gridWidth: 140,
      gridHeight: 100,
      cellSize: 5,
      boundary: 'fixed',
      kLeak: 0.05,
      kCoupling: 0.11,
      kRelease: 0.7,
      closeMode: 'timed',
      minOpenTicks: 4,
      resetPeriod: 10,
      membraneInit: 'seeded-spike',
      overlay: 'voltage',
      stepsPerSecond: 30,
    },
  },
  {
    name: 'Membrane — chatter (deliberate failure mode)',
    description:
      'Near-zero hysteresis band, tiny k_release and minOpenTicks = 0: gates chatter at the comparator boundary.',
    config: {
      mode: 'membrane-only',
      gridWidth: 120,
      gridHeight: 80,
      cellSize: 6,
      boundary: 'fixed',
      vThreshold: -55,
      vClose: -55.5,
      vRelease: -75,
      kLeak: 0.05,
      kCoupling: 0.06,
      kRelease: 0.06,
      closeMode: 'hysteresis',
      minOpenTicks: 0,
      resetPeriod: 0,
      membraneInit: 'noisy-rest',
      membraneJitter: 6,
      overlay: 'voltage',
      stepsPerSecond: 20,
    },
  },
  {
    name: 'Membrane — PID homeostat (accommodation)',
    description:
      'The per-cell PID replaces the leak term: I accumulates as adaptation, D gives rate sensitivity (§6.3).',
    config: {
      mode: 'pid-homeostat',
      gridWidth: 140,
      gridHeight: 100,
      cellSize: 5,
      boundary: 'fixed',
      vTarget: -70,
      kp: 0.06,
      ki: 0.004,
      kd: 0.05,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      vThreshold: -55,
      vClose: -60,
      vRelease: -90,
      kCoupling: 0.09,
      kRelease: 0.6,
      closeMode: 'hysteresis',
      minOpenTicks: 2,
      resetPeriod: 9,
      membraneInit: 'seeded-spike',
      overlay: 'voltage',
      stepsPerSecond: 30,
    },
  },
  // ---------------------------------------------------------------------
  // Dither-CA: palette colours as states, seeking a target colour (§11)
  // ---------------------------------------------------------------------
  {
    name: 'Dither-CA — monochrome gradient',
    description:
      'Black & white palette chasing a diagonal gradient. Every cell regulates the mean colour of its 3×3 neighbourhood toward the local target tone, so a dither pattern self-organises out of noise.',
    config: {
      mode: 'dither',
      gridWidth: 160,
      gridHeight: 110,
      cellSize: 4,
      boundary: 'fixed',
      neighborhood: 'moore',
      radius: 1,
      ditherSource: 'gradient',
      ditherColorA: '#000000',
      ditherColorB: '#ffffff',
      ditherGradient: 'diagonal',
      ditherPalette: '#000000,#ffffff',
      ditherMetric: 'rgb',
      ditherIncludeSelf: true,
      ditherHysteresis: 0.03,
      ditherTemperature: 0,
      ditherUpdateRate: 1,
      ditherInit: 'random',
      kp: 1,
      ki: 0.05,
      kd: 0.2,
      integralClamp: true,
      integralMin: -2,
      integralMax: 2,
      overlay: 'none',
      stepsPerSecond: 20,
    },
  },
  {
    name: 'Dither-CA — Game Boy sunrise (radial)',
    description:
      'Four-green handheld palette approximating a warm radial glow. Toggle "Show target" to compare the texture with the colour field it is averaging toward.',
    config: {
      mode: 'dither',
      gridWidth: 160,
      gridHeight: 144,
      cellSize: 4,
      boundary: 'fixed',
      ditherSource: 'gradient',
      ditherColorA: '#f6f6c8',
      ditherColorB: '#0a1a0a',
      ditherGradient: 'radial',
      ditherPalette: '#0f380f,#306230,#8bac0f,#9bbc0f',
      ditherMetric: 'perceptual',
      ditherIncludeSelf: true,
      ditherHysteresis: 0.04,
      ditherTemperature: 0,
      ditherUpdateRate: 0.7,
      ditherInit: 'nearest',
      kp: 1,
      ki: 0.04,
      kd: 0.25,
      integralClamp: true,
      integralMin: -2,
      integralMax: 2,
      stepsPerSecond: 24,
    },
  },
  {
    name: 'Dither-CA — PICO-8 rainbow, radius 2',
    description:
      'Sixteen colours, a 5×5 neighbourhood and a strong integral term: colour-mixing textures crawl across a horizontal gradient the palette cannot reproduce directly.',
    config: {
      mode: 'dither',
      gridWidth: 180,
      gridHeight: 110,
      cellSize: 4,
      boundary: 'toroidal',
      neighborhood: 'moore',
      radius: 2,
      ditherSource: 'gradient',
      ditherColorA: '#ff004d',
      ditherColorB: '#29adff',
      ditherGradient: 'horizontal',
      ditherPalette:
        '#000000,#1d2b53,#7e2553,#008751,#ab5236,#5f574f,#c2c3c7,#fff1e8,' +
        '#ff004d,#ffa300,#ffec27,#00e436,#29adff,#83769c,#ff77a8,#ffccaa',
      ditherMetric: 'perceptual',
      ditherIncludeSelf: true,
      ditherHysteresis: 0.05,
      ditherTemperature: 0.01,
      ditherUpdateRate: 0.5,
      ditherInit: 'random',
      kp: 1.2,
      ki: 0.08,
      kd: 0.3,
      integralClamp: true,
      integralMin: -1.5,
      integralMax: 1.5,
      stepsPerSecond: 24,
    },
  },
  {
    name: 'Dither-CA — annealing greys (stochastic)',
    description:
      'Four grey levels chosen by a seeded softmin: a non-zero temperature keeps the texture simmering while the asynchronous update rate lets it settle into a smooth vertical ramp.',
    config: {
      mode: 'dither',
      gridWidth: 140,
      gridHeight: 100,
      cellSize: 5,
      boundary: 'fixed',
      ditherSource: 'gradient',
      ditherColorA: '#ffffff',
      ditherColorB: '#000000',
      ditherGradient: 'vertical',
      ditherPalette: '#000000,#555555,#aaaaaa,#ffffff',
      ditherIncludeSelf: true,
      ditherHysteresis: 0.02,
      ditherTemperature: 0.08,
      ditherUpdateRate: 0.35,
      ditherInit: 'first',
      kp: 1,
      ki: 0.02,
      kd: 0.1,
      integralClamp: true,
      integralMin: -1,
      integralMax: 1,
      stepsPerSecond: 30,
    },
  },
  {
    name: 'Dither-CA — shimmering (no hysteresis, hot D)',
    description:
      'Deliberately restless: zero hysteresis, synchronous update and a large derivative gain make the neighbourhood means overshoot, producing rippling moiré over a solid colour.',
    config: {
      mode: 'dither',
      gridWidth: 140,
      gridHeight: 100,
      cellSize: 5,
      boundary: 'toroidal',
      ditherSource: 'solid',
      ditherColorA: '#6f8fb0',
      ditherPalette: '#000000,#ff2079,#04d9ff,#ccff00',
      ditherIncludeSelf: false,
      ditherHysteresis: 0,
      ditherTemperature: 0,
      ditherUpdateRate: 1,
      ditherInit: 'random',
      kp: 1.4,
      ki: 0.01,
      kd: 1.5,
      integralClamp: true,
      integralMin: -1,
      integralMax: 1,
      overlay: 'u',
      overlayScale: 1,
      overlayAlpha: 0.35,
      stepsPerSecond: 30,
    },
  },
  {
    name: 'Dither-CA — your picture (upload or URL)',
    description:
      'Image target with a risograph palette. Open "Dither (colour target)" → "Upload image…" (or paste a same-origin / CORS image URL), then press "Palette from target" to let k-means pick the inks.',
    config: {
      mode: 'dither',
      gridWidth: 200,
      gridHeight: 140,
      cellSize: 4,
      boundary: 'fixed',
      ditherSource: 'image',
      ditherImageUrl: '',
      ditherImageFit: 'cover',
      ditherColorA: '#f4efe6',
      ditherColorB: '#0078bf',
      ditherGradient: 'diagonal',
      ditherPalette: '#f4efe6,#ff6f61,#0078bf,#ffe800',
      ditherMetric: 'perceptual',
      ditherIncludeSelf: true,
      ditherHysteresis: 0.04,
      ditherTemperature: 0,
      ditherUpdateRate: 0.8,
      ditherInit: 'random',
      kp: 1,
      ki: 0.05,
      kd: 0.2,
      integralClamp: true,
      integralMin: -2,
      integralMax: 2,
      stepsPerSecond: 24,
    },
  },
];

export default PRESETS;
