/**
 * presets.js — named configurations illustrating the behaviour classes of §10.
 * Each `config` is a partial patch applied over the current configuration.
 */

export const PRESETS = [
  {
    name: 'Default — binary threshold',
    description: 'Balanced starting point: 2-state, Moore(1), T = 4, mild integral memory.',
    config: {
      gridWidth: 120,
      gridHeight: 80,
      boundary: 'toroidal',
      neighborhood: 'moore',
      radius: 1,
      targetMode: 'constant',
      target: 4,
      kp: 1,
      ki: 0.02,
      kd: 0.4,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.35,
      stepsPerSecond: 20,
      overlay: 'none',
      cellSize: 6,
    },
  },
  {
    name: 'Under-damped ripples',
    description:
      'High Kp, low Kd: rippling wavefronts, oscillatory density rings, breathing clusters.',
    config: {
      kp: 2.4,
      ki: 0.01,
      kd: 0.05,
      integralClamp: true,
      integralMin: -6,
      integralMax: 6,
      target: 4,
      targetMode: 'constant',
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.4,
      stepsPerSecond: 24,
      overlay: 'none',
    },
  },
  {
    name: 'Critically-damped blobs',
    description: 'Balanced Kp/Kd: stable blobs, smooth morphogenesis, self-maintaining textures.',
    config: {
      kp: 0.9,
      ki: 0.015,
      kd: 0.85,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      target: 4,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.3,
      stepsPerSecond: 20,
      overlay: 'none',
    },
  },
  {
    name: 'Over-damped glassy creep',
    description: 'High Kd: slow creep, frozen-in patterns, metastable glassy states.',
    config: {
      kp: 0.35,
      ki: 0.005,
      kd: 2.2,
      integralClamp: true,
      integralMin: -10,
      integralMax: 10,
      target: 4,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.45,
      stepsPerSecond: 12,
      overlay: 'none',
    },
  },
  {
    name: 'Frustration vortices (I-field)',
    description:
      'Strong integral term with clamping; diagnostic overlay shows the accumulated-error field.',
    config: {
      kp: 0.5,
      ki: 0.18,
      kd: 0.25,
      integralClamp: true,
      integralMin: -6,
      integralMax: 6,
      target: 3.5,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      overlay: 'integral',
      overlayScale: 6,
      initialCondition: 'random',
      initialDensity: 0.3,
      stepsPerSecond: 18,
    },
  },
  {
    name: 'Semantic regulatory modes (3-state)',
    description:
      'State colour reports which PID term dominates: teal = integral-dominant, amber = P/D-driving.',
    config: {
      kp: 1.1,
      ki: 0.06,
      kd: 0.5,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      target: 4,
      stateCardinality: 3,
      expression: 'semantic',
      theta: 0,
      activePredicate: 'gt0',
      initialCondition: 'random',
      initialDensity: 0.32,
      overlay: 'none',
      stepsPerSecond: 20,
    },
  },
  {
    name: 'Quantised bands (3-state)',
    description: 'Ternary magnitude quantisation of u_t with band edges a < b.',
    config: {
      kp: 1.2,
      ki: 0.02,
      kd: 0.4,
      target: 4,
      stateCardinality: 3,
      expression: 'quantize',
      bandA: -0.6,
      bandB: 1.2,
      activePredicate: 'gt0',
      initialCondition: 'random',
      initialDensity: 0.3,
      stepsPerSecond: 20,
    },
  },
  {
    name: 'Stochastic annealing',
    description:
      'Probabilistic expression: σ(u_t) activation, soft boundaries, noise-driven exploration.',
    config: {
      kp: 0.8,
      ki: 0.02,
      kd: 0.3,
      target: 4,
      stateCardinality: 2,
      expression: 'probabilistic',
      theta: 0,
      sigmoidScale: 1.6,
      initialCondition: 'random',
      initialDensity: 0.35,
      stepsPerSecond: 20,
      overlay: 'none',
    },
  },
  {
    name: 'Programmable morphogenesis (radial T)',
    description: 'Spatially varying target field: dense core, sparse rim — shape-guided growth.',
    config: {
      gridWidth: 140,
      gridHeight: 100,
      cellSize: 5,
      targetMode: 'radial',
      target: 4,
      targetAmplitude: 3,
      kp: 1,
      ki: 0.03,
      kd: 0.5,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'center',
      initialDensity: 0.7,
      stepsPerSecond: 20,
      overlay: 'error',
      overlayScale: 6,
    },
  },
  {
    name: 'Breathing target (oscillating T)',
    description:
      'Time-varying target drives global density oscillation; watch the error overlay pulse.',
    config: {
      targetMode: 'oscillating',
      target: 4,
      targetAmplitude: 2,
      targetPeriod: 200,
      kp: 1.1,
      ki: 0.02,
      kd: 0.45,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.35,
      overlay: 'u',
      overlayScale: 6,
      stepsPerSecond: 30,
    },
  },
  {
    name: 'Self-healing texture (paint to damage)',
    description:
      'Stable texture with fixed borders — clear a region by shift-dragging and watch it regrow.',
    config: {
      boundary: 'fixed',
      neighborhood: 'moore',
      radius: 1,
      kp: 0.9,
      ki: 0.04,
      kd: 0.7,
      integralClamp: true,
      integralMin: -8,
      integralMax: 8,
      target: 4,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.35,
      cellSize: 8,
      gridWidth: 90,
      gridHeight: 60,
      stepsPerSecond: 15,
    },
  },
  {
    name: 'Wide von Neumann radius 3',
    description:
      'Larger neighbourhood with a proportionally larger target: coarse, slow-moving structure.',
    config: {
      neighborhood: 'vonNeumann',
      radius: 3,
      target: 7,
      kp: 0.7,
      ki: 0.02,
      kd: 0.5,
      stateCardinality: 2,
      expression: 'threshold',
      theta: 0,
      initialCondition: 'random',
      initialDensity: 0.4,
      stepsPerSecond: 15,
    },
  },
];

export default PRESETS;
